tasks #2,#3,#4
js-tasks-ru/js-20220905_alex-n pull request #2
Opened 2022-09-09 08:15 UTC by nas8

Implementations of functions:
- sortStrings,
- pick,
- omit.

2022-09-09 08:16 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-09 21:23 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return arrCopy.sort(collator.compare).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-09 21:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'asc') {
устраните дубликаы кода в данном решении

2022-09-09 21:24 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let i = 0; i < arr.length; i++) {
есть более удобный способ итерации по массиву: `for...of`

2022-09-09 21:24 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let j = 0; j < fields.length; j++) {
замените данный цикл на метод `includes`

2022-09-09 21:25 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const arr = Object.entries(obj);
внесите правки по аналогии с решение `pick`

2022-09-09 21:25 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-10 18:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-11 15:07 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let item of arr) {
`const item`

2022-09-11 15:08 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>    let sortedObj = {};
`const`

2022-09-11 15:08 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      sortedObj[ item[0] ] = item[1];
для того чтобы не обращаться по индексам, можно использовать деструктурирование:
```
for (const [key, value] of arr) {
...
```

2022-09-11 15:08 UTC, dosandk approved these changes
good 👍

2022-09-11 15:09 UTC, merged